# Generated by Django 4.2.9 on 2025-06-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scholar_url', models.URLField(blank=True, verbose_name='Google Scholar URL')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True, verbose_name='Conference Website')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('pdf_url', models.URLField(blank=True, verbose_name='PDF Link')),
                ('hf_url', models.URLField(blank=True, verbose_name='HuggingFace Link')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Link')),
                ('project_url', models.URLField(blank=True, verbose_name='Project/Webpage Link')),
                ('publication_date', models.DateField()),
                ('authors', models.ManyToManyField(through='main.Authorship', to='main.author')),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='main.conference')),
                ('tags', models.ManyToManyField(blank=True, related_name='papers', to='main.tag')),
            ],
        ),
        migrations.AddField(
            model_name='authorship',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paper'),
        ),
        migrations.AlterUniqueTogether(
            name='authorship',
            unique_together={('paper', 'author')},
        ),
    ]
