# Generated by Django 4.2.9 on 2026-08-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='model',
            field=models.CharField(blank=True, help_text='Gemini model for this conversation. Blank falls back to GEMINI_MODEL.', max_length=100),
        ),
    ]
