# Generated by Django 5.2.17 on 2026-10-08 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_chatsession_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaction',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Blank for actions staged through the HTTP API (assistant.api), which has no chat session.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='assistant.chatsession'),
        ),
    ]
