# Generated by Django 4.2.9 on 2024-02-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('phone_suffix', models.CharField(default='+39', max_length=6)),
                ('state', models.CharField(choices=[('PD', 'Pending'), ('NO', 'No'), ('YE', 'Yes'), ('+1', 'Yes plus one')], default='PD', max_length=2)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('fuorisede', models.BooleanField(default=False)),
            ],
        ),
    ]
