# Generated by Django 4.2.9 on 2025-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
    ]
