# Generated by Django 4.2.9 on 2025-06-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgements', '0002_fakeacknowledgement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=255, unique=True)),
                ('ack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acknowledgements.acknowledgement')),
            ],
        ),
    ]
