# Generated by Django 4.2.9 on 2025-06-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgements', '0003_linkacknowledgement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeAcknowledgement',
        ),
        migrations.RemoveField(
            model_name='acknowledgement',
            name='text',
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='html',
            field=models.TextField(default='', help_text='Full acknowledgement text stored as raw HTML.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='password',
            field=models.CharField(default='', help_text='Password for accessing the acknowledgement (consider hashing).', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='question',
            field=models.CharField(default='', help_text='Security question associated with this acknowledgement.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkacknowledgement',
            name='ack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='acknowledgements.acknowledgement'),
        ),
    ]
