# Generated by Django 4.2.9 on 2025-06-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgements', '0004_delete_fakeacknowledgement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgement',
            name='password',
            field=models.CharField(blank=True, help_text='Password for accessing the acknowledgement (consider hashing).', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgement',
            name='question',
            field=models.CharField(blank=True, help_text='Security question associated with this acknowledgement.', max_length=255, null=True),
        ),
    ]
