# Generated by Django 4.1.7 on 2024-09-17 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_study_vatrpp', '0002_remove_competitor_csv_file_competitor_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iam_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sampleimage',
            constraint=models.UniqueConstraint(fields=('competitor', 'iam_id'), name='unique_competitor_iamid'),
        ),
        migrations.AddField(
            model_name='skipped',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_study_vatrpp.player'),
        ),
    ]
