# Generated by Django 4.2.9 on 2024-01-14 11:18

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('origin_x', models.IntegerField(default=0)),
                ('origin_y', models.IntegerField(default=0)),
                ('origin_orentation', models.IntegerField(choices=[(0, 'North'), (1, 'East'), (2, 'South'), (3, 'West')], default=0)),
                ('img', models.ImageField(upload_to=game.models.upload_map)),
                ('walls_img', models.ImageField(upload_to=game.models.upload_walls)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.map')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('dst_x', models.IntegerField(default=0)),
                ('dst_y', models.IntegerField(default=0)),
                ('dst_orentation', models.IntegerField(choices=[(0, 'North'), (1, 'East'), (2, 'South'), (3, 'West')], default=0)),
                ('dst_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_map', to='game.map')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.map')),
            ],
        ),
    ]
