# Generated by Django 4.2.9 on 2024-01-14 12:39

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_dst_orentation_door_dst_orientation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('spritesheet', models.ImageField(upload_to=game.models.upload_sprites)),
            ],
        ),
    ]
