# Generated by Django 4.2.9 on 2025-01-24 15:08

from django.db import migrations, models
import django.db.models.deletion
import user_study_emuru.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reference', models.BooleanField(default=False)),
                ('winner', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accuracy', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('correct_control_answers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iam_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_study_emuru.player')),
            ],
        ),
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=1024, upload_to=user_study_emuru.models.content_file_name)),
                ('available', models.BooleanField(default=True)),
                ('iam_id', models.IntegerField()),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_study_emuru.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_study_emuru.player')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='user_study_emuru.sampleimage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sampleimage',
            constraint=models.UniqueConstraint(fields=('competitor', 'iam_id'), name='unique_competitor_iamid'),
        ),
    ]
