# Generated by Django 4.2.9 on 2025-01-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_study_emuru', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sampleimage',
            name='unique_competitor_iamid',
        ),
        migrations.RemoveField(
            model_name='sampleimage',
            name='iam_id',
        ),
        migrations.RemoveField(
            model_name='skipped',
            name='iam_id',
        ),
        migrations.AddField(
            model_name='sampleimage',
            name='shtg_key',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='skipped',
            name='shtg_key',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddConstraint(
            model_name='sampleimage',
            constraint=models.UniqueConstraint(fields=('competitor', 'shtg_key'), name='unique_competitor_shtg_key'),
        ),
    ]
