# Generated by Django 4.2.9 on 2024-09-15 17:54

from django.db import migrations, models
import django.db.models.deletion
import user_study_mad.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('winner', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accuracy', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('correct_control_answers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_text', models.CharField(max_length=128, unique=True)),
                ('ita_text', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=1024, upload_to=user_study_mad.models.content_file_name)),
                ('exclude_from_study', models.BooleanField(default=False)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_study_mad.competitor')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_study_mad.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_control', models.BooleanField(default=False)),
                ('sample_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_a', to='user_study_mad.sampleimage')),
                ('sample_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_b', to='user_study_mad.sampleimage')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_study_mad.player')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_study_mad.question')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='user_study_mad.sampleimage')),
            ],
        ),
    ]
