# Generated by Django 4.2.9 on 2024-01-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('h', 'Happy'), ('b', 'Bored'), ('s', 'Sad')], max_length=1)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('h', 'Happy'), ('b', 'Bored'), ('s', 'Sad')], max_length=1)),
                ('description', models.CharField(max_length=280)),
                ('tears', models.ManyToManyField(to='tears.tears')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tears.user')),
            ],
        ),
    ]
