# Generated by Django 4.2.9 on 2024-01-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='tears',
            field=models.ManyToManyField(blank=True, to='tears.tears'),
        ),
    ]
