# Generated by Django 4.2.9 on 2024-01-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0002_alter_day_tears'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='description',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
