# Generated by Django 4.2.9 on 2024-01-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0003_alter_day_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
