# Generated by Django 4.2.9 on 2024-01-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0005_remove_tears_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tears',
            name='status',
            field=models.CharField(choices=[('h', 'Happy'), ('b', 'Bored'), ('s', 'Sad')], default='h', max_length=1),
        ),
    ]
