# Generated by Django 4.2.9 on 2025-12-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('guessed_in_current_round', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('playing', 'Playing'), ('finished', 'Finished')], default='setup', max_length=10)),
                ('current_round', models.IntegerField(choices=[(1, 'Round 1: Open Description'), (2, 'Round 2: One Word'), (3, 'Round 3: The Mime')], default=1)),
                ('current_team_index', models.IntegerField(default=0)),
                ('current_turn_start', models.DateTimeField(blank=True, null=True)),
                ('turn_duration', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score_round1', models.IntegerField(default=0)),
                ('score_round2', models.IntegerField(default=0)),
                ('score_round3', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='timesup.game')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('cluegiver', 'Cluegiver'), ('guesser', 'Guesser')], default='guesser', max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='timesup.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('guessed_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesup.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_records', to='timesup.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_records', to='timesup.team')),
            ],
            options={
                'ordering': ['guessed_at'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='timesup.game'),
        ),
    ]
