# Generated by Django 4.2.9 on 2025-12-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(choices=[('red', 'Red Team'), ('blue', 'Blue Team'), ('green', 'Green Team'), ('yellow', 'Yellow Team')], default='red', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('game', 'color')},
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
