# Generated by Django 4.1.7 on 2025-12-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesup', '0002_team_color_alter_team_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='round_order',
            field=models.IntegerField(default=0),
        ),
    ]
